# Generated by Django 4.0.4 on 2022-06-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addss',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
