# Generated by Django 4.0.4 on 2022-06-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_addss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='addss',
        ),
    ]
