# Generated by Django 4.0.4 on 2022-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_addss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
