# Generated by Django 4.0.4 on 2022-06-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_contacts_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='pic',
        ),
    ]
